name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' tests
    steps:
      - uses: actions/checkout@v3
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: echo "${{ secrets.DOTENV }}" > .env && npm ci && npm run test
